### ISSUE TITLE
Android 6 : App crashes when i start a radio

### ISSUE THREAD

**Issue by Go-rom** [jamal2362/URL-Radio#26]
Hi,

i just upgraded from 8.9 to 9.1 on my Android 6 phone (Samsung J3 2015)
Now it crashes when i start a webradio.

9.0 is also affected.

For now, i'm keeping 8.9 which works fine so nothing critical.
If you need a log file, just tell me how i can get it.

Thanks for this great app btw !

**Comment by jamal2362** [comment]
Hey,
Please give me logs while you start the radio.

**Comment by Go-rom** [comment]
Hi

Here's the crash log

`FATAL EXCEPTION: main
Process: com.jamal2367.urlradio, PID: 7991
java.lang.NoClassDefFoundError: d6.l
	at com.jamal2367.urlradio.PlayerService.g(SourceFile:64)
	at com.jamal2367.urlradio.PlayerService$e.u0(SourceFile:172)
	at k1.b0.c(SourceFile:25)
	at h1.l.run(SourceFile:50)
	at h1.m.b(SourceFile:67)
	at k1.e0.h1(SourceFile:112)
	at k1.e0.g1(SourceFile:69)
	at k1.e0.r(SourceFile:20)
	at e1.e.g(SourceFile)
	at e1.p.g(SourceFile)
	at e1.p.g(SourceFile)
	at b3.z2.g(SourceFile:4)
	at l1.c.accept(SourceFile)
	at k1.g0.f(SourceFile:18)
	at b3.k2.run(SourceFile)
	at b3.d.run(SourceFile:34)
	at h1.y.F(SourceFile:26)
	at b3.e.b(SourceFile:50)
	at d0.g.run(SourceFile:657)
	at h1.y.F(SourceFile:26)
	at b3.t2.j0(SourceFile:46)
	at h1.k.handleMessage(SourceFile:87)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by jamal2362** [comment]
Hey @Go-rom 

Can you try this test apk?
https://files.fm/f/azf33csvs

Please let me know.

**Comment by Go-rom** [comment]
The apk has been tested for several hours, no crash. Seems to be allright to me, thanks 👍

**Comment by jamal2362** [comment]
Great to hear that!

Now you can use the newest 9.3 release. 
The fix is included in the Release.

I close this now because it's resolved :)
