### ISSUE TITLE
Graceful Handling of Revoked/Unavailable Network

### ISSUE THREAD

**Issue by githububub** [jamal2362/URL-Radio#38]
When network is revoked or unavailable and stream playback is requested, URL-Radio 9.6 crashes with the following:

```
type: crash
osVersion: google/oriole/oriole:13/T2B3.230109.009/2023031300:user/release-keys
package: com.jamal2367.urlradio:96
process: com.jamal2367.urlradio
processUptime: 22057 + 254 ms

java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'ExoPlayer:Playback'
Expected thread: 'main'
See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
	at k1.d0.m1(SourceFile:95)
	at k1.d0.q(SourceFile:1)
	at e1.e.g(Unknown Source:4)
	at e1.o.g(Unknown Source:2)
	at com.jamal2367.urlradio.PlayerService$e.a(SourceFile:22)
	at q1.x.g(SourceFile:39)
	at u1.j$c.handleMessage(SourceFile:81)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

Suggest a toast or snackbar message indicating the lack of network connectivity as a way to handle the issue versus an outright crash. Pixel 6 GrapheneOS.

**Comment by jamal2362** [comment]
Fixed:
https://github.com/jamal2362/URL-Radio/commit/ef7829194d18bfe303fa295bb61b235b6e580334

**Comment by githububub** [comment]
Confirmed resolved.
